<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>TroiletProt_DotNet</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <BaseOutputPath>$(SolutionDir)Plugins</BaseOutputPath>
    <GenerateDocumentationFile>False</GenerateDocumentationFile>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\TroiletCore\TroiletCore.csproj">
      <Private>False</Private>
    </ProjectReference>
  </ItemGroup>

  <ItemGroup>
    <Reference Include="dnlib">
      <HintPath>..\Dependencies\dnlib.dll</HintPath>
      <Private>False</Private>
    </Reference>
  </ItemGroup>

</Project>
