<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <RootNamespace>TroiletProt_DotNet</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <BaseOutputPath>$(SolutionDir)Plugins</BaseOutputPath>
    <GenerateDocumentationFile>False</GenerateDocumentationFile>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Resources\AbstractClass.svg" />
    <None Remove="Resources\Event.svg" />
    <None Remove="Resources\EventPrivate.svg" />
    <None Remove="Resources\EventProtected.svg" />
    <None Remove="Resources\Field.svg" />
    <None Remove="Resources\FieldPrivate.svg" />
    <None Remove="Resources\FieldProtected.svg" />
    <None Remove="Resources\ILIcon.png" />
    <None Remove="Resources\Interface.svg" />
    <None Remove="Resources\Method.svg" />
    <None Remove="Resources\MethodPrivate.svg" />
    <None Remove="Resources\MethodProtected.svg" />
    <None Remove="Resources\Property.svg" />
    <None Remove="Resources\PropertyPrivate.svg" />
    <None Remove="Resources\PropertyProtected.svg" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Resources\AbstractClass.svg" />
    <EmbeddedResource Include="Resources\Event.svg" />
    <EmbeddedResource Include="Resources\EventPrivate.svg" />
    <EmbeddedResource Include="Resources\EventProtected.svg" />
    <EmbeddedResource Include="Resources\Field.svg" />
    <EmbeddedResource Include="Resources\FieldPrivate.svg" />
    <EmbeddedResource Include="Resources\FieldProtected.svg" />
    <EmbeddedResource Include="Resources\ILIcon.png" />
    <EmbeddedResource Include="Resources\Interface.svg" />
    <EmbeddedResource Include="Resources\Method.svg" />
    <EmbeddedResource Include="Resources\MethodPrivate.svg" />
    <EmbeddedResource Include="Resources\MethodProtected.svg" />
    <EmbeddedResource Include="Resources\Property.svg" />
    <EmbeddedResource Include="Resources\PropertyPrivate.svg" />
    <EmbeddedResource Include="Resources\PropertyProtected.svg" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\TroiletCore\TroiletCore.csproj">
      <Private>False</Private>
    </ProjectReference>
  </ItemGroup>

  <ItemGroup>
    <Reference Include="dnlib">
      <HintPath>..\Dependencies\dnlib.dll</HintPath>
      <Private>False</Private>
    </Reference>
  </ItemGroup>

</Project>
