<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>TroiletProt_Lua</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <BaseOutputPath>$(SolutionDir)Plugins</BaseOutputPath>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Resources\LuaIcon.png" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Resources\LuaIcon.png" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\TroiletCore\TroiletCore.csproj">
      <Private>False</Private>
    </ProjectReference>
  </ItemGroup>

  <ItemGroup>
    <Reference Include="LuaLibV2">
      <HintPath>..\Dependencies\LuaLibV2.dll</HintPath>
      <Private>False</Private>
    </Reference>
  </ItemGroup>

</Project>
